on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '立即构建'
        required: true
        default: 'true'
name: RUN BUILD
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - name: Clone Source
      run: |
        git clone --depth=1 https://github.com/pobthebuilder/resolve-flatpak.git blackmagic --recursive

    # - name: Cloudupload
    #   id: cloudupload
    #   run: |
    #     curl -fsSL git.io/file-transfer | sh
    #     # wet < 2GB
    #     # gg
    #     # gof
    #     ./transfer gg --no-progress blackmagic/com.blackmagic.Resolve.yaml 2>&1 | tee cloudupload.log
    #     echo "url=$(cat cloudupload.log | grep https | cut -f3 -d' ')" >> $GITHUB_OUTPUT
    # - name: upload cloudupload url
    #   run: |
    #     echo ${{ steps.cloudupload.outputs.url }}
    #     test_xxx


    - name: Download File
      run: |
        cd blackmagic
        sed -i '/sha256/d' com.blackmagic.Resolve.yaml
        sed -i 's/18\.1\.2_Linux.run/18\.1\.1_Linux.run/' com.blackmagic.Resolve.yaml
        dnf install -y wget
        wget https://downloads.blackmagicdesign.com/DaVinci_Resolve/18.1.1/DaVinci_Resolve_18.1.1_Linux.zip -O DaVinci_Resolve_18.1.2_Linux.zip
        ls -lah DaVinci_Resolve_18.1.2_Linux.zip
    - name: flatpak action
      uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: com.blackmagic.Resolve.flatpak
        manifest-path: blackmagic/com.blackmagic.Resolve.yaml
        cache-key: flatpak-builder1811

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: com.blackmagic.Resolve.flatpak
        path: com.blackmagic.Resolve.flatpak
        compression-level: 0
        if-no-files-found: error
